# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb16f9607df05e5f00f869184a9c076e7ff49e695f86cdc50b28dc71bb2588e7cbc5e1604af98b06a81d822fee3ecf61c2f1f9209aa29a952913b07be14d4d6f

test:
  secret_key_base: 41268815172dd984ca65db7952840a2024fba6d135146b081523c7a55cb82aa60d266505dad8cb51132f8fdf912acb3c3c4c7bb497984d5fc1112e7323ea0e3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
